development:
  adapter: postgresql
  encoding: unicode
  database: blog_development
  pool: 5
  host: localhost
  username: ryanmgallagher
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: blog_test
  pool: 5
  host: localhost
  username: ryanmgallagher
  password: